### ISSUE TITLE
How to use without the 32khz crystal

### ISSUE THREAD

**Issue by drewcassidy** [ARMmbed/target-nrf51dk-gcc#10]
How would I change this config to use the internal 32khz RC oscillator?

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSFW-2269

**Comment by ddavidebor** [comment]
Take a look at row 38 of targe.json here https://github.com/fermiumlabs/target-nrf51bareic-gcc
You can also use the entire target if you like, it's made to use a bare IC with 16k of ram (instead of 32), the S110 softdevice (instead of S310) and i will keep it updated with interesting pin descriptions.
